- name: Install iptables
  tags: Firewall
  ansible.builtin.apt:
    name: iptables-persistent
    state: latest

- name: ACCEPT INPUT ESTABLISHED,RELATED
  tags: Firewall
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    chain_management: true
    state: present
    action: append
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: 'ESTABLISHED,RELATED'
  notify: save_rules

- name: ACCEPT INPUT loopback
  tags: Firewall
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    chain_management: true
    state: present
    action: append
    in_interface: lo
    jump: ACCEPT
    comment: 'loopback'
  notify: save_rules

- name: ACCEPT INPUT PING IPv4
  tags: Firewall
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    chain_management: true
    state: present
    action: append
    protocol: icmp
    jump: ACCEPT
    comment: 'ICMP'
    ip_version: ipv4
  notify: save_rules

- name: ACCEPT FORWARD ESTABLISHED,RELATED
  tags: Firewall
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: 'ESTABLISHED,RELATED'
  notify: save_rules

- name: ACCEPT FORWARD PING IPv4
  tags: Firewall
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: icmp
    jump: ACCEPT
    comment: 'ICMP'
    ip_version: ipv4
  notify: save_rules

# Add acces for admin(s) CIDR
- name: ACCEPT INPUT LIMIT SSH IPv4
  tags: Firewall
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_port: 22
    source: '{{ item }}'
    ctstate: NEW
    syn: match
    limit: 2/second
    limit_burst: 20
    jump: ACCEPT
    comment: 'SSH'
    ip_version: ipv4
  loop:
    - '{{ ADMIN_CIDR_1 }}'
    - '{{ ADMIN_CIDR_2 }}'
    - '{{ ADMIN_CIDR_3 }}'
  notify: save_rules

# Add Firewalls defaults policy IPv4
- name: DEFAULT DROP INPUT POLICY
  tags: Firewall
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    chain_management: true
    state: present
    action: append
    policy: DROP
    comment: 'DROP INCOMING'
    ip_version: both
  notify: save_rules

- name: DEFAULT DROP FORWARD POLICY
  tags: Firewall
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    policy: DROP
    comment: 'DROP ROUTED'
    ip_version: both
  notify: save_rules

- name: DEFAULT ACCEPT OUTPUT POLICY
  tags: Firewall
  ansible.builtin.iptables:
    table: filter
    chain: OUTPUT
    chain_management: true
    state: present
    action: append
    policy: ACCEPT
    comment: 'ACCEPT OUTGOING'
    ip_version: both
  notify: save_rules
