---
- name: Install SNMPD
  ansible.builtin.apt:
    name:
      - snmpd
    state: latest
    update_cache: yes

- name: Enable SNMPD Interfaces Access
  ansible.builtin.copy:
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      sysLocation   {{ ansible_fqdn }}
      sysContact    {{ SNMP_CONTACT }}
      sysServices   72
      agentaddress  udp:0.0.0.0:161,udp6:[::]:161
      view          all included .1
      rocommunity   {{ SNMP_COMMUNITY }} default -V all
      rocommunity6  {{ SNMP_COMMUNITY }} default -V all
  notify: restart_snmpd

