
- name: Setting email notification
  ansible.builtin.lineinfile:
    dest: /etc/fail2ban/jail.local
    regexp: "^destemail ="
    line: "destemail = {{ EMAIL_NOTIFICATION }}"
  notify: restart_fail2ban

- name: Setting email origin
  ansible.builtin.lineinfile:
    dest: /etc/fail2ban/jail.local
    regexp: "^sender ="
    line: "sender = root@{{ ansible_fqdn }}"
  notify: restart_fail2ban

- name: Setting MTA to use
  ansible.builtin.lineinfile:
    dest: /etc/fail2ban/jail.local
    regexp: "^mta = "
    line: 'mta = mail'
  notify: restart_fail2ban

- name: Setting email notification action
  ansible.builtin.lineinfile:
    dest: /etc/fail2ban/jail.local
    regexp: "^action = %(action_)s"
    line: 'action = %(action_mwl)s'
  notify: restart_fail2ban
