- name: Hardening SSH service
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config.d/SecureSSH.conf
    create: yes
    block: |
      Port 22
      AddressFamily inet
      HostKey /etc/ssh/ssh_host_rsa_key
      HostKey /etc/ssh/ssh_host_ed25519_key
      PermitRootLogin no
      MaxAuthTries 1
      MaxSessions 2
      PubkeyAuthentication yes
      PasswordAuthentication no
      PermitEmptyPasswords no
      KbdInteractiveAuthentication no
      X11Forwarding no
      AuthenticationMethods publickey
      KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com      
  notify: restart_ssh
