- name: Install fail2ban
  ansible.builtin.apt:
    name:
      - fail2ban
    state: latest

- name: Check if a local config file exist
  ansible.builtin.stat:
    path: /etc/fail2ban/jail.local
  register: file_check

- name: Create a local config file it's not exist
  ansible.builtin.copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: true
    owner: root
    group: root
    mode: '0644'
  when: file_check.stat.exists == false

- name: Change Ban Time
  ansible.builtin.lineinfile:
    dest: /etc/fail2ban/jail.local
    regexp: "^bantime  = 10m"
    line: 'bantime  = 10h'
  notify: restart_fail2ban

- name: Change Max Retry
  ansible.builtin.lineinfile:
    dest: /etc/fail2ban/jail.local
    regexp: "^maxretry = 5"
    line: 'maxretry = 3'
  notify: restart_fail2ban

- name: Config fail2ban log
  ansible.builtin.copy:
    dest: /etc/logrotate.d/fail2ban
    owner: root
    group: root
    mode: '0644'
    content: |
      /var/log/fail2ban.log {
        daily
        dateext
        dateformat -%Y%m%d-%H%M%S
        missingok
        rotate 365
        compress
        delaycompress
        su root root
        create 640 root adm
        postrotate
          fail2ban-client flushlogs 1>/dev/null
        endscript
      }

- name: Enable SSH protection for brute force
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/jail.local
    insertafter: '^\[sshd\]'
    line: 'enabled = true'
    state: present
  notify: restart_fail2ban
