- name: Enable reverse path filtering for new network
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/90-kernel.conf

- name: Enable reverse path filtering for current network
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/90-kernel.conf

- name: Enable Log Martian Packets on all IPv4 Interfaces
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/90-kernel.conf

- name: Specifies the maximum number of TCP connections
  ansible.posix.sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 2048
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/90-kernel.conf

- name: Number of SYN packets the Kernel will send before giving up on the new connection
  ansible.posix.sysctl:
    name: net.ipv4.tcp_synack_retries
    value: 2
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/90-kernel.conf

- name: Cantidad de reintentos de envío del paquete SYN para establecer una nueva conexion
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syn_retries
    value: 5
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/90-kernel.conf

- name: Ignore Bogus ICMP Error Responses on IPv4 Interfaces
  ansible.posix.sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/90-kernel.conf

- name: Ensure TCP SYN Cookies is enabled
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/90-kernel.conf

- name: Enables the endpoints to keep a current measurement of the round-trip time (RTT) of the network between them
  ansible.posix.sysctl:
    name: net.ipv4.tcp_timestamps
    value: 0
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/90-kernel.conf
