---
- name: Check if Gitea Keyring archive are downloaded
  ansible.builtin.stat:
    path: /etc/apt/trusted.gpg.d/morph027-gitea.asc
  register: file_check

- name: Download Gitea Keyring archive
  ansible.builtin.get_url:
    url: "https://packaging.gitlab.io/gitea/gpg.key"
    dest: "/etc/apt/trusted.gpg.d/morph027-gitea.asc"
    owner: "root"
    group: "root"
    mode: '0755'
    use_proxy: yes
  when: file_check.stat.exists == false

- name: Add debian main repositories
  ansible.builtin.deb822_repository:
    name: morph027-gitea
    types: deb
    uris: "https://packaging.gitlab.io/gitea/"
    suites:
      - gitea
    components:
      - main
    architectures: amd64
    signed_by: /etc/apt/trusted.gpg.d/morph027-gitea.asc
    state: present

- name: Install gitea
  ansible.builtin.apt:
    name:
      - gitea
      - morph027-keyring
    state: latest
    update_cache: yes

- name: Start Gitea
  ansible.builtin.systemd_service:
    name: gitea.service
    masked: no
    enabled: true
    state: started

- name: Check if Gitea Keyring archive are downloaded
  ansible.builtin.stat:
    path: /etc/apt/apt.conf.d/52unattended-upgrades
  register: file_check

- name: Setting gitea Unattended Upgrade
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/52gitea-upgrades
    owner: root
    group: root
    mode: '0644'
    content: |
      Unattended-Upgrade::Allowed-Origins {"morph027:gitea";};
  notify: restart_unattended
  when: file_check.stat.exists == true

