---
- name: Copy template of APT config file
  ansible.builtin.template:
    src: apt.conf.j2
    dest: /etc/apt/apt.conf

- name: Copy template of ceph.list config file
  ansible.builtin.template:
    src: ceph.list.j2
    dest: /etc/apt/sources.list.d/ceph.list

- name: Copy template of pve-enterprise.list config file
  ansible.builtin.template:
    src: pve-enterprise.list.j2
    dest: /etc/apt/sources.list.d/pve-enterprise.list

- name: Copy template of sources.list config file
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list

- name: Copy template of pve-no-subscription.list config file
  ansible.builtin.template:
    src: pve-no-subscription.list.j2
    dest: /etc/apt/sources.list.d/pve-no-subscription.list

- name: update repository index and upgrade the system
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes

- name: install some tools (vim-nox, tmux)
  ansible.builtin.apt:
    name:
      - vim-nox
      - tmux
    state: present

- name: Download new CT template
  ansible.builtin.get_url:
    url: "http://download.proxmox.com/images/system/{{ ostemplate_name }}"
    dest: "/var/lib/vz/template/cache/{{ ostemplate_name}}"

- name: Create a user Terraform
  ansible.builtin.lineinfile:
    dest: /etc/pve/user.cfg
    regexp: ’^user\:Terraform’
    line: 'user:Terraform@pam:1:0::::::'

- name: Add group for Terraform if not exists and assigned to the user of Terraform
  ansible.builtin.lineinfile:
    dest: /etc/pve/user.cfg
    regexp: ’^group\:Terraform’
    line: 'group:Terraform:Terraform@pam::'

- name: Add rol for Terraform if not exists
  ansible.builtin.lineinfile:
    dest: /etc/pve/user.cfg
    regexp: ’^role\:Terraform’
    line: 'role:Terraform:Datastore.AllocateSpace,Datastore.Audit,Pool.Allocate,SDN.Use,Sys.Audit,Sys.Console,Sys.Modify,Sys.PowerMgmt,VM.Allocate,VM.Audit,VM.Clone,VM.Config.CDROM,VM.Config.CPU,VM.Config.Cloudinit,VM.Config.Disk,VM.Config.HWType,VM.Config.Memory,VM.Config.Network,VM.Config.Options,VM.Migrate,VM.Monitor,VM.PowerMgmt:'

- name: Assign rol Terraform to the group of Terraform
  ansible.builtin.lineinfile:
    dest: /etc/pve/user.cfg
    regexp: ’\@Terraform\:Terraform’
    line: 'acl:100:/:@Terraform:Terraform:'

#- name: Create rol for Terraform
#  ansible.builtin.command:
#    cmd: pveum role add Terraform -privs "Datastore.AllocateSpace, Datastore.Audit, Pool.Allocate, SDN.Use, Sys.Audit, Sys.Console, Sys.Modify, Sys.PowerMgmt, VM.Allocate, VM.Audit, VM.Clone, VM.Config.CDROM, VM.Config.CPU, VM.Config.Cloudinit, VM.Config.Disk, VM.Config.HWType, VM.Config.Memory, VM.Config.Network, VM.Config.Options, VM.Migrate, VM.Monitor, VM.PowerMgmt"

#- name: Create group for Terraform
#  ansible.builtin.command:
#    cmd: pveum group add Terraform

#- name: Assign rol Terraform to the group of Terraform
#  ansible.builtin.command:
#    cmd: pveum aclmod / -group Terraform -role Terraform

#- name: Create a user Terraform and assigned to the group of Terraform
#  ansible.builtin.command:
#    cmd: pveum user add Terraform@pam -group Terraform

