- name: config repositories self-hosted check date valid until
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      acquire::check-valid-until "0";
