all:
  vars:
  hosts:
    hermes: # VM with internet
      ansible_host: 190.92.127.229
  children:
    debian:
      vars:
        SUDO_USER_NAME: 'erki'
        SUDO_USER_PASS: '~/.ssh/mitrans_sudo_user_pass.txt'
        SUDO_USER_PUB_KEY: '~/.ssh/mitrans_key.pub'
        SNMP_CONTACT: 'adminred@nc.mitrans.gob.cu'
        SNMP_COMMUNITY: 'mitrans_etecsa'
        debian_repositories_main:     'deb.debian.org'
        debian_repositories_security: 'security.debian.org'
      hosts:
      children:
        proxmox:
          vars:
            proxmox_repositories:         'download.proxmox.com'
          hosts:
        debselfhosted:
          vars:
            debian_self_hosted_find:      '^192\.168\.56\.1 deb'
            debian_self_hosted_hosts:     '192.168.56.1 debian.homelab.cu security.homelab.cu'
            debian_repositories_main:     'debian.homelab.cu'
            debian_repositories_security: 'security.homelab.cu'
          hosts:
          children:
            pveselfhosted:
              vars:
                proxmox_self_hosted_find:   '^192\.168\.56\.1 pro'
                proxmox_self_hosted_hosts:  '192.168.56.1 proxmox.homelab.cu'
                proxmox_repositories:       'proxmox.homelab.cu'
              hosts:
        server:
          vars:
            EMAIL_NOTIFICATION: 'adminred@nc.mitrans.gob.cu'
            SSH_CIDR_1: '0.0.0.0/0'
            SSH_CIDR_2: '0.0.0.0/0'
            SSH_CIDR_3: '0.0.0.0/0'
            SNMP_CIDR_1: '0.0.0.0/0'
            SNMP_CIDR_2: '0.0.0.0/0'
            SNMP_CIDR_3: '0.0.0.0/0'
          hosts:
          children:
            dns:
              vars:
                DNS_CIDR_1: '0.0.0.0/0'
                DNS_CIDR_2: '0.0.0.0/0'
                DNS_CIDR_3: '0.0.0.0/0'
              hosts:
              children:
                edge:
                  vars:
                    named_conf_external_zone:     'mitrans_vps.external-zone'
                    named_conf_external_zone_dir: 'mitrans_vps.external-zone.dir'
                    named_conf_external_zone_inv: 'mitrans_vps.external-zone.inv'
                  hosts:
                    hermes:
            web:
              vars:
                WEB_CIDR_1: '0.0.0.0/0'
                WEB_CIDR_2: '0.0.0.0/0'
                WEB_CIDR_3: '0.0.0.0/0'
              hosts:
            database:
              vars:
              hosts:
            lamp:
              vars:
              hosts:
              children:
                nextcloud:
                  vars:
                    NEXTCLOUD_HOST_ALIAS: 'nextcloud'
                    NEXTCLOUD_ADMIN_USER: 'admin'
                    NEXTCLOUD_ADMIN_PASS: 'admin'
                    NEXTCLOUD_DATABASE_USER: 'nextcloud'
                    NEXTCLOUD_DATABASE_PASS: 'nextcloud'
                  hosts:
                wordpress:
                  vars:
                    WORDPRESS_HOST_ALIAS: 'wordpress'
                    WORDPRESS_ADMIN_USER: 'admin'
                    WORDPRESS_ADMIN_PASS: 'admin'
                    WORDPRESS_DATABASE_USER: 'wordpress'
                    WORDPRESS_DATABASE_PASS: 'wordpress'
                  hosts:
                zabbix:
                  vars:
                    ZABBIX_HOST_ALIAS: 'zabbix'
                    ZABBIX_DATABASE_USER: 'zabbix'
                    ZABBIX_DATABASE_PASS: 'zabbix'
                  hosts:
