---

- name: selfhosted configuration
  tags: selfhosted
  hosts:
    - debselfhosted
  roles:
    - debian-selfhosted-repositories

- name: debian base system
  tags: server
  hosts:
    - server
  roles:
    - debian-base-system

- name: debian service gitea
  tags: gitea
  hosts:
    - gitea
  roles:
    - service-gitea-enable

- name: debian service gitea
  tags: giteacuba
  hosts:
    - giteacuba
  roles:
    - service-gitea-enable-with-proxy

- name: debian service docker.io and compose
  tags: docker
  hosts:
    - docker
  roles:
    - service-docker-enable

