all:
  vars:
  hosts:
    testing: # CT with internet
      ansible_host: 10.245.77.116
  children:
    debian:
      vars:
        SUDO_USER_NAME: 'admin'
        SUDO_USER_PASS: '~/.ssh/homelab_sudo_user_pass.txt'
        SUDO_USER_PUB_KEY: '~/.ssh/homelab_key.pub'
        debian_repositories_main:     'deb.debian.org'
        debian_repositories_security: 'security.debian.org'
      hosts:
      children:
        debselfhosted:
          vars:
            debian_self_hosted_find:      '^10\.245\.77\.1 deb'
            debian_self_hosted_hosts:     '10.245.77.1 debian.homelab.cu security.homelab.cu'
            debian_repositories_main:     'debian.homelab.cu'
            debian_repositories_security: 'security.homelab.cu'
          hosts:
            testing:
        server:
          vars:
            FQDN_EMAIL_SERVER: 'smtp.gmail.com'
            EMAIL_NOTIFICATION: 'admin@homelab.cu'
            SSH_CIDR_1: '0.0.0.0/0'
            SSH_CIDR_2: '0.0.0.0/0'
            SSH_CIDR_3: '0.0.0.0/0'
          hosts:
          children:
            docker:
              vars:
              hosts:
                testing:
