all:
  vars:
  hosts:
    testing: # CT with internet
      ansible_host: 10.245.77.48
  children:
    debian:
      vars:
        SUDO_USER_NAME: 'admin'
        SUDO_USER_PASS: '~/.ssh/homelab_sudo_user_pass.txt'
        SUDO_USER_PUB_KEY: '~/.ssh/homelab_key.pub'
        debian_repositories_main:     'deb.debian.org'
        debian_repositories_security: 'security.debian.org'
      hosts:
      children:
        debselfhosted:
          vars:
            debian_self_hosted_find:      '^10\.245\.77\.1 deb'
            debian_self_hosted_hosts:     '10.245.77.1 debian.homelab.cu security.homelab.cu'
            debian_repositories_main:     'debian.homelab.cu'
            debian_repositories_security: 'security.homelab.cu'
          hosts:
            testing:
        server:
          vars:
            FQDN_EMAIL_SERVER: 'smtp.gmail.com'
            EMAIL_NOTIFICATION: 'admin@homelab.cu'
            SSH_CIDR_1: '0.0.0.0/0'
            SSH_CIDR_2: '0.0.0.0/0'
            SSH_CIDR_3: '0.0.0.0/0'
          hosts:
          children:
            psiphon:
              hosts:
              children:
                giteacuba:
                  vars:
                    proxy_env:
                      socks_proxy: http://127.0.0.1:1081/
                      https_proxy: http://127.0.0.1:8081/
                      http_proxy: http://127.0.0.1:8081/
                      ftp_proxy: http://127.0.0.1:8081/
                      no_proxy: 127.0.0.1,homelab.cu
                      SOCKS_PROXY: http://127.0.0.1:1081/
                      HTTPS_PROXY: http://127.0.0.1:8081/
                      HTTP_PROXY: http://127.0.0.1:8081/
                      FTP_PROXY: http://127.0.0.1:8081/
                      NO_PROXY: 127.0.0.1,homelab.cu
                    GITEA_CIDR_1: '0.0.0.0/0'
                    GITEA_CIDR_2: '0.0.0.0/0'
                    GITEA_CIDR_3: '0.0.0.0/0'
                    GITEA_DATABASE_USER: 'gitea'
                    GITEA_DATABASE_PASS: 'gitea'
                  hosts:
                    testing:
            gitea:
              vars:
                GITEA_CIDR_1: '0.0.0.0/0'
                GITEA_CIDR_2: '0.0.0.0/0'
                GITEA_CIDR_3: '0.0.0.0/0'
                GITEA_DATABASE_USER: 'gitea'
                GITEA_DATABASE_PASS: 'gitea'
              hosts:
            docker:
              vars:
              hosts:
