---

- name: selfhosted configuration
  tags: selfhosted
  hosts:
    - debselfhosted
  roles:
    - debian-selfhosted-repositories

- name: debian base system
  tags: server
  hosts:
    - server
  roles:
    - debian-base-system

- name: debian service docker.io and compose
  tags: docker
  hosts:
    - docker
  roles:
    - docker-debian-enable
