all:
  children:
    homelab:
      hosts:
        laptop:
          ansible_host: 192.168.56.1
        srv01:
          ansible_host: 192.168.56.2
        pve:
          ansible_host: 192.168.56.9
    clients:
      hosts:
        laptop:
    servers:
      vars:
        debian_self_hosted_find:  '^192\.168\.56\.1 deb'
        debian_self_hosted_hosts: '192.168.56.1 deb.debian.org security.debian.org'
      hosts:
        srv01:
    proxmoxs:
      vars:
        debian_self_hosted_find:   '^192\.168\.56\.1 deb'
        debian_self_hosted_hosts:  '192.168.56.1 deb.debian.org security.debian.org'
        proxmox_self_hosted_find:  '^192\.168\.56\.1 dow'
        proxmox_self_hosted_hosts: '192.168.56.1 download.proxmox.com'
      hosts:
        pve:
