all:
  children:
    self_hosted:
      vars:
        debian_self_hosted_find:   '^192\.168\.56\.1 deb'
        debian_self_hosted_hosts:  '192.168.56.1 deb.debian.org security.debian.org'
        proxmox_self_hosted_find:  '^192\.168\.56\.1 dow'
        proxmox_self_hosted_hosts: '192.168.56.1 download.proxmox.com'
        ADMIN_CIDR_1: '192.168.56.1/32'
        ADMIN_CIDR_2: '192.168.56.1/32'
        ADMIN_CIDR_3: '192.168.56.1/32'
        EMAIL_NOTIFICATION: 'admin1@homelab.cu'
      hosts:
        laptop:
          ansible_host: 192.168.56.1
        srv01:
          ansible_host: 192.168.56.2
        pve:
          ansible_host: 192.168.56.9
    clients:
      hosts:
        laptop:
    servers:
      hosts:
        srv01:
    proxmoxs:
      hosts:
        pve:
