all:
  vars:
  hosts:
    pve:  # Proxmox Virtual Enviroment
      ansible_host: 192.168.56.9
    ct00: # CT without internet
      ansible_host: 192.168.56.10
    ct01: # CT with internet
      ansible_host: 192.168.56.11
    ct02: # CT nextcloud without internet
      ansible_host: 192.168.56.12
    vm00: # VM without internet
      ansible_host: 192.168.56.20
    vm01: # VM with internet
      ansible_host: 192.168.56.21
  children:
    debian:
      vars:
        SUDO_USER_NAME: 'admin'
        SUDO_USER_PASS: '~/.ssh/homelab_sudo_user_pass.txt'
        SUDO_USER_PUB_KEY: '~/.ssh/homelab_key.pub'
        SNMP_CONTACT: 'monitor@homelab.cu'
        SNMP_COMMUNITY: 'homelab'
        debian_repositories_main:     'deb.debian.org'
        debian_repositories_security: 'security.debian.org'
      hosts:
      children:
        proxmox:
          vars:
            proxmox_repositories:         'download.proxmox.com'
          hosts:
            pve:
        debselfhosted:
          vars:
            debian_self_hosted_find:      '^192\.168\.56\.1 deb'
            debian_self_hosted_hosts:     '192.168.56.1 debian.homelab.cu security.homelab.cu'
            debian_repositories_main:     'debian.homelab.cu'
            debian_repositories_security: 'security.homelab.cu'
          hosts:
            ct00:
          children:
            pveselfhosted:
              vars:
                proxmox_self_hosted_find:   '^192\.168\.56\.1 pro'
                proxmox_self_hosted_hosts:  '192.168.56.1 proxmox.homelab.cu'
                proxmox_repositories:       'proxmox.homelab.cu'
              hosts:
                pve:
        server:
          vars:
            EMAIL_NOTIFICATION: 'admin@homelab.cu'
            SSH_CIDR_1: '192.168.56.1/32'
            SSH_CIDR_2: '192.168.56.1/32'
            SSH_CIDR_3: '192.168.56.1/32'
            SNMP_CIDR_1: '192.168.56.1/32'
            SNMP_CIDR_2: '192.168.56.1/32'
            SNMP_CIDR_3: '192.168.56.1/32'
          hosts:
          children:
            dns_edge:
              vars:
                named_conf_external_zone:     'named.conf.external-zone'
                named_conf_external_zone_dir: 'named.conf.external-zone.dir'
                named_conf_external_zone_inv: 'named.conf.external-zone.inv'
                DNS_CIDR_1: '0.0.0.0/0'
                DNS_CIDR_2: '0.0.0.0/0'
                DNS_CIDR_3: '0.0.0.0/0'
              hosts:
                ct00:
            web:
              vars:
                WEB_CIDR_1: '0.0.0.0/0'
                WEB_CIDR_2: '0.0.0.0/0'
                WEB_CIDR_3: '0.0.0.0/0'
              hosts:
            database:
              vars:
              hosts:
            lamp:
              vars:
              hosts:
              children:
                nextcloud:
                  vars:
                    NEXTCLOUD_HOST_ALIAS: 'nextcloud'
                    NEXTCLOUD_ADMIN_USER: 'admin'
                    NEXTCLOUD_ADMIN_PASS: 'admin'
                    NEXTCLOUD_DATABASE_USER: 'nextcloud'
                    NEXTCLOUD_DATABASE_PASS: 'nextcloud'
                  hosts:
                wordpress:
                  vars:
                    WORDPRESS_HOST_ALIAS: 'wordpress'
                    WORDPRESS_ADMIN_USER: 'admin'
                    WORDPRESS_ADMIN_PASS: 'admin'
                    WORDPRESS_DATABASE_USER: 'wordpress'
                    WORDPRESS_DATABASE_PASS: 'wordpress'
                  hosts:
                zabbix:
                  vars:
                    ZABBIX_HOST_ALIAS: 'zabbix'
                    ZABBIX_DATABASE_USER: 'zabbix'
                    ZABBIX_DATABASE_PASS: 'zabbix'
                  hosts:
