---

- name: config proxmoxs servers
  hosts:
    - proxmoxs
  roles:
    - self-hosted/repositories/proxmox
    - repositories/proxmox
    - self-hosted/repositories/debian
    - repositories/date
    - repositories/debian
    - repositories/upgrade/manual
    - repositories/upgrade/unattended

- name: config debians servers
  hosts:
    - servers
  roles:
    - self-hosted/repositories/debian
    - repositories/date
    - repositories/debian
    - repositories/upgrade/manual
    - repositories/upgrade/unattended
    - security/system/sysctl/hosts
    - security/firewall/iptables/init/hosts
    - services/send-only/postfix/enable
    - repositories/upgrade/email-notification

