---

- name: config debian repositories self-hosted
  tags: self-hosted
  hosts:
    - servers
  roles:
    - self-hosted/repositories/debian

- name: config proxmox repositories self-hosted
  tags: self-hosted
  hosts:
    - proxmoxs
  roles:
    - self-hosted/repositories/proxmox

- name: repositories self-hosted check date valid until
  tags: self-hosted
  hosts:
    - servers
    - proxmoxs
  roles:
    - repositories/date

- name: debian repositories
  tags: repositories
  hosts:
    - servers
  roles:
    - repositories/debian

- name: proxmox repositories
  tags: repositories
  hosts:
    - proxmoxs
  roles:
    - repositories/proxmox

- name: upgrade distribution
  tags: upgrade
  hosts:
    - servers
    - proxmoxs
  roles:
    - repositories/upgrade


