---
- name: Install sudo
  ansible.builtin.apt:
    name:
      - sudo
    state: latest
    update_cache: yes

- name: Ensure group for new user exists
  ansible.builtin.group:
    name: "{{ SUDO_USER_NAME }}"
    state: present

- name: Create a new user inside sudo group
  ansible.builtin.user:
    name: "{{ SUDO_USER_NAME }}"
    password: "{{ lookup('file', SUDO_USER_PASS) }}"
    state: present
    createhome: yes
    groups: "{{ SUDO_USER_NAME }},users,sudo"
    shell: /bin/bash

- name: Add new user public key 
  ansible.builtin.authorized_key:
    user: "{{ SUDO_USER_NAME }}"
    key: "{{ lookup('file', SUDO_USER_PUB_KEY) }}"
    state: present

