---
- name: Check if Psiphon for Linux are installed
  ansible.builtin.stat:
    path: /usr/bin/psiphon
  register: file_check

- name: Install wget
  ansible.builtin.apt:
    name:
      - wget
    state: latest
    update_cache: yes
  when: file_check.stat.exists == false

- name: Download Psiphon for Linux archive
  get_url:
    url: "https://raw.githubusercontent.com/SpherionOS/PsiphonLinux/main/plinstaller2"
    dest: "/tmp/plinstaller2"
    owner: "root"
    group: "root"
    mode: '0755'
  when: file_check.stat.exists == false

- name: Installing Psiphon for Linux
  ansible.builtin.shell: |
    sh /tmp/plinstaller2
  when: file_check.stat.exists == false

- name: Delete obsolete config file
  ansible.builtin.file:
    path: /tmp/plinstaller2
    state: absent

- name: Creating Psiphon for Linux Service
  ansible.builtin.copy:
    dest: /etc/systemd/system/psiphond.service
    owner: root
    group: root
    mode: '0755'
    content: |
      [Unit]
      After=network.target
      [Service]
      ExecStart=/usr/bin/psiphon run
      Type=simple
      WorkingDirectory=/root
      [Install]
      WantedBy=default.target

- name: Start Psiphond
  ansible.builtin.systemd_service:
    name: psiphond.service
    masked: no
    enabled: true
    state: started
